import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "./Layout/Layout";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Djanat Documentation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + `bg-[#D6D6D6]`}>
        <GoogleOAuthProvider
          clientId={process.env.GOOGLE_OAUTH_CLIENT_ID ?? ""}
        >
          <Layout>{children}</Layout>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
